package api

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/prometheus/client_golang/prometheus/promhttp"

	"github.com/christopherime/schedularr/internal/api/gen"
	"github.com/christopherime/schedularr/internal/api/middleware"
)

// readyzTimeout bounds how long /readyz waits on the store's SELECT 1
// round-trip before reporting not-ready, so a wedged database can't hang a
// caller's readiness probe indefinitely.
const readyzTimeout = 5 * time.Second

// Config configures the bearer-auth gate NewRouter applies to /api/v1/*.
type Config struct {
	// Token is the bearer token required on /api/v1/* requests
	// (Authorization: Bearer <token>). middleware.BearerAuth enforces a
	// 32-character minimum; NewRouter returns an error if Token is shorter
	// than that (including empty) unless InsecureNoAuth is set.
	Token string

	// InsecureNoAuth skips bearer-auth on /api/v1/* entirely. NewRouter
	// logs a WARN when this is set, since every /api/v1 endpoint (blocks
	// CRUD, schedule apply, series-state patch, ...) becomes reachable by
	// anyone who can reach the listener. Meant for local development only,
	// never a real deployment.
	InsecureNoAuth bool
}

// NewRouter builds the full HTTP handler for the Schedularr API server.
//
// Four endpoints are served unauthenticated and outside the
// RequestID/Logging/Recovery/BearerAuth chain entirely, so health and
// metrics probes stay cheap and never depend on a caller having a token:
//
//   - GET /healthz     -- process liveness only, no dependency checks.
//   - GET /readyz      -- liveness plus a bounded store round-trip
//     (store.Store.Ping, i.e. `SELECT 1`); 503 problem+json if the store
//     isn't reachable within readyzTimeout.
//   - GET /metrics     -- Prometheus text exposition via
//     promhttp.Handler(), scraping the same default registry
//     internal/metrics registers its collectors to.
//   - GET /openapi.json -- the OpenAPI contract itself, marshaled straight
//     from gen.GetSpec() so it can never drift from what internal/api/gen
//     actually implements.
//
// Everything else is generated by gen.HandlerFromMux from d (via
// NewHandlers), mounted under /api/v1 on a chi sub-router wrapped
// RequestID -> Logging -> Recovery -> BearerAuth (outermost to innermost --
// see each middleware's own doc comment for why that order matters:
// RequestID must run before Logging so a request id already exists to log,
// and Logging must wrap Recovery so a recovered panic's 500 still gets
// logged with the right status). BearerAuth is the innermost layer, right
// before the real handler; it's included unless cfg.InsecureNoAuth is set.
//
// NewRouter itself performs no I/O and never blocks. Constructing
// middleware.BearerAuth is its only fallible step, so -- with
// InsecureNoAuth false -- the returned error is always a token-validation
// error: Token is empty or shorter than 32 characters.
func NewRouter(cfg Config, d Deps) (http.Handler, error) {
	if d.Logger == nil {
		d.Logger = slog.Default()
	}

	var authMW func(http.Handler) http.Handler
	if cfg.InsecureNoAuth {
		d.Logger.Warn("api server starting with bearer authentication disabled (--insecure-no-auth); every /api/v1 endpoint is reachable without a token")
	} else {
		mw, err := middleware.BearerAuth(cfg.Token)
		if err != nil {
			return nil, fmt.Errorf("api: %w", err)
		}
		authMW = mw
	}

	r := chi.NewRouter()

	r.Get("/healthz", healthzHandler)
	r.Get("/readyz", readyzHandler(d))
	r.Handle("/metrics", promhttp.Handler())
	r.Get("/openapi.json", openAPIHandler(d.Logger))

	h := NewHandlers(d)
	r.Route("/api/v1", func(sr chi.Router) {
		sr.Use(middleware.RequestID)
		sr.Use(middleware.Logging(d.Logger))
		sr.Use(middleware.Recovery(d.Logger))
		if authMW != nil {
			sr.Use(authMW)
		}
		gen.HandlerFromMux(h, sr)
	})

	return r, nil
}

// healthzHandler reports process liveness only -- no dependency checks --
// so it's cheap enough to hit on every probe interval even under load.
func healthzHandler(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte("ok"))
}

// readyzHandler reports whether d.Store is reachable, via a
// readyzTimeout-bounded SELECT 1 round-trip (store.Store.Ping). A failure
// is logged server-side -- the underlying driver error isn't repeated to
// the caller, matching the internal-error convention used by the rest of
// this package (see e.g. GetStatus in tunarr.go) -- and reported as 503
// problem+json.
func readyzHandler(d Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx, cancel := context.WithTimeout(r.Context(), readyzTimeout)
		defer cancel()

		if err := d.Store.Ping(ctx); err != nil {
			d.Logger.Error("readyz: store unreachable", "error", err)
			WriteProblem(w, r, http.StatusServiceUnavailable, "not ready", "store unavailable")
			return
		}

		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	}
}

// openAPIHandler serves the OpenAPI contract as JSON, straight from the
// generated spec (gen.GetSpec() -- the non-deprecated equivalent of
// gen.GetSwagger()) rather than a separately maintained copy of
// api/openapi.yaml, so it can never drift from what internal/api/gen
// actually implements.
func openAPIHandler(l *slog.Logger) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		spec, err := gen.GetSpec()
		if err != nil {
			l.Error("openapi.json: failed to load spec", "error", err)
			WriteProblem(w, r, http.StatusInternalServerError, "internal server error", "")
			return
		}

		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(spec); err != nil {
			l.Error("openapi.json: failed to encode spec", "error", err)
		}
	}
}
